### ISSUE TITLE
Diferent Width

### ISSUE THREAD

**Issue by lucoceano** [kronik/SpiralPullToRefresh#1]
When I change this line:

``` objective-c
//#define ScreenWidth  [[UIScreen mainScreen] bounds].size.width
```

to:

``` objective-c
#define ScreenWidth  self.frame.size.width
```

it's calculate the first and last particle wrong, and they don't appear on the correct point.

![ios simulator screen shot 6 may 2013 22 49 58](https://f.cloud.github.com/assets/1299301/469243/ba0d7a24-b6b8-11e2-96e7-4b385137969c.png)

**Comment by kronik** [comment]
Thanks! I've changed the code.
