### ISSUE TITLE
Center square doesn't appear?

### ISSUE THREAD

**Issue by ghost** [kronik/SpiralPullToRefresh#2]
I need some help if I want to customize it to look like the twitter music instead of the spiral where should I start? 
// default styling values
        self.autoresizingMask = UIViewAutoresizingFlexibleWidth;
        self.currentState = SpiralPullToRefreshStateStopped;

```
    self.backgroundColor = [UIColor blackColor];
    self.clipsToBounds = YES;
```

I am guessing after this snippet the next would be where I would need to change so it is different animation? I was wondering if you tired to do it like twitter music app? Like how all the square come from the side instead of the spiral. I don't know how to do it myself and I just wanted to learn from your source. I am still a noob! Also I noticed the center square doesn't appear?

**Comment by kronik** [comment]
Hi! 

Magic starts from line 476: 
- (void) contentOffsetChanged:(float)contentOffset {

... to get next particles positions it takes contentOffset and pass it to inner for loop to update every particle position:

particleView.center = ...

currently algorithm to calculate current position is based on moving a point on a circle formula: x = x1 + r \* cos (angle); y = y1 - r *sin (angle), where x1, y1 - coordinates of the circle center, r - circle radius and angle is current angle. 

So just use your own algo to calculate every particle position based on current content offset and that's it!

Good luck!
