### ISSUE TITLE
Make circles possible

### ISSUE THREAD

**Issue by ffried** [kronik/SpiralPullToRefresh#3]
First of all: Really great work you've done here!

I played around with it a little bit and if you add the following code to the end of your `initWithFrame:frame` method there will be circles instead of squares.

```
for (UIView *particle in _particles) {
            particle.layer.cornerRadius = particle.frame.size.height / 2;
            particle.layer.masksToBounds = YES;
        }
```

And if you add a boolean property the user can choose which to take.
If you want I can fork the repo and do it for you. Just tell me if you even want it...

**Comment by kronik** [comment]
Thanks! This is just a skeleton component and app... Feel free to customize it however you want :)
