### ISSUE TITLE
iOS 7 support

### ISSUE THREAD

**Issue by ffried** [kronik/SpiralPullToRefresh#4]
I just started with making my app compatible with iOS 7 and noticed that SpiralPullToRefresh isn't working correctly with iOS 7 even though I set the contentOffset correctly. It's still behind the navigation bar. Using the UIRefreshControl of iOS everything's fine.
I had no time yet to dive into your code yet. I wanted to ask if you already know the problem or if you're even working on a fix?

**Comment by kronik** [comment]
Hi, yes this is known issue. And I'm going to upload update soon.

**Comment by iebox** [comment]
I'm facing the same issue, could you please update the fix? thanks a million!
