### ISSUE TITLE
Transparent Navigation Bar

### ISSUE THREAD

**Issue by alexsaidani** [kronik/SpiralPullToRefresh#5]
There are issues if you have the navigation bar set to transparent along with using this, it is always hidden behind the navigation bar as it ignores it if its transparent and takes the top of the screen instead. Also if you then refresh in this state it will move the content up to the top so part of it is hidden by the navigation bar.

There's probably an easy fix by just changing the offset or whatever, but thought i'd point it out. I'll add a fix if I find it later.

**Comment by kronik** [comment]
Yes, this is known issue. Simply have no time to fix it now.... Pull requests are welcome too :)
